# Generated by Django 5.1.6 on 2025-03-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_slug_project_unique_slug_per_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
