# Generated by Django 5.1.6 on 2025-03-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_lists', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'title'), name='unique_list_per_project')],
            },
        ),
    ]
