# Generated by Django 5.1.6 on 2025-03-13 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_list_created_on_list_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='projects.project'),
        ),
    ]
