# Generated by Django 5.1.6 on 2025-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='depends_on',
            field=models.ManyToManyField(blank=True, to='projects.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
