# Generated by Django 5.1.6 on 2025-02-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planban', '0002_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
